name: intagram_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  firebase_storage: ^10.3.8
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  uuid: ^3.0.6
  flutter_staggered_grid_view: ^0.4.1
  path_provider: ^2.0.11

  flutter: 
    sdk: flutter
  mockito: ^5.3.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter
  integration_test:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

